### ISSUE TITLE
Update to latest kimai

### ISSUE THREAD

**Issue by mantenie** [mwaeckerlin/kimai#2]
The version of kimai used in the Dockerfile is outdated. It would be nice if it can be changed to version 1.1.0.

**Comment by mwaeckerlin** [comment]
I've just seen that there is a pull request for kimai 0.9.3, so I'll first accept that.

Is it sufficient to change the download link?

@mantenie could you test the upgrade?

**Comment by mwaeckerlin** [comment]
Implemented with b087f28f2f85d91c7ae614b749cbcfcddb4f721a.

Now, on each rebuild, it downloads the latest Kimai, so it should be always more or less up to date.

I tested just the first login. Please report any new issues.
